# Generated by Django 4.2.7 on 2023-12-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('gender', models.IntegerField(max_length=10)),
                ('address', models.TextField(max_length=200)),
                ('password', models.TextField(max_length=200)),
                ('is_verified', models.IntegerField(default=0)),
                ('otp', models.CharField(max_length=6)),
                ('is_enabled', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'donors',
            },
        ),
    ]
