# Generated by Django 4.2.7 on 2023-12-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcessFoodApp', '0002_alter_donor_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
