# Generated by Django 4.2.7 on 2023-12-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcessFoodApp', '0004_alter_donor_address_alter_donor_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=10)),
                ('ingredients', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200, null=True)),
                ('image', models.ImageField(default=None, max_length=200, upload_to='product_images/')),
                ('is_enabled', models.IntegerField(default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'foods',
            },
        ),
    ]
