# Generated by Django 4.2.7 on 2023-12-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcessFoodApp', '0005_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='donor_id',
            field=models.IntegerField(null=True),
        ),
    ]
