# Generated by Django 4.2.7 on 2023-12-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcessFoodApp', '0006_food_donor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='ingredients',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
