# Generated by Django 4.2.7 on 2023-12-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcessFoodApp', '0007_alter_food_ingredients_alter_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='ingredients',
            field=models.TextField(null=True),
        ),
    ]
