# Generated by Django 4.2.7 on 2023-12-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcessFoodApp', '0008_alter_food_description_alter_food_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(default=None, max_length=200, upload_to='food_images/'),
        ),
    ]
