# Generated by Django 4.2.7 on 2023-12-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcessFoodApp', '0009_alter_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(default=None, max_length=250, upload_to='food_images/'),
        ),
    ]
