# Generated by Django 4.2.7 on 2023-12-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcessFoodApp', '0010_alter_donor_created_date_alter_food_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('gender', models.IntegerField(null=True)),
                ('address', models.TextField(max_length=200, null=True)),
                ('password', models.TextField(max_length=200, null=True)),
                ('is_verified', models.IntegerField(default=0)),
                ('otp', models.CharField(max_length=6, null=True)),
                ('is_enabled', models.IntegerField(default=1)),
                ('created_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
