# Generated by Django 4.2.7 on 2023-12-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcessFoodApp', '0011_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.IntegerField()),
                ('donor_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('ratings', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('is_enabled', models.IntegerField(default=1)),
                ('created_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'ratings',
            },
        ),
    ]
