# Generated by Django 4.2.7 on 2023-12-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcessFoodApp', '0012_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='updated_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='updated_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='updated_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_date',
            field=models.DateTimeField(null=True),
        ),
    ]
