# Generated by Django 4.2.7 on 2023-12-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcessFoodApp', '0013_donor_updated_date_food_updated_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(null=True)),
                ('food_id', models.IntegerField()),
                ('donor_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('address', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('order_status', models.IntegerField(default=1)),
                ('is_rated', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(null=True)),
                ('updated_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.AddField(
            model_name='rating',
            name='order_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='ratings',
            field=models.IntegerField(null=True),
        ),
    ]
