# Generated by Django 3.2.23 on 2023-12-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcessFoodApp', '0016_auto_20231227_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_expaired',
            field=models.IntegerField(default=0),
        ),
    ]
