# Generated by Django 3.2.23 on 2023-12-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcessFoodApp', '0017_food_is_expaired'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_type', models.IntegerField(default=0)),
                ('food_name', models.CharField(max_length=200, null=True)),
                ('food_type', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('quantity', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('req_status', models.IntegerField(default=1)),
                ('is_delivered', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(null=True)),
                ('updated_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'requests',
            },
        ),
    ]
