# Generated by Django 3.2.23 on 2023-12-27 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExcessFoodApp', '0018_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='UserRequest',
        ),
    ]
