# Generated by Django 3.2.23 on 2023-12-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcessFoodApp', '0020_alter_userrequest_req_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='image',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='QR_CODE/'),
        ),
    ]
