# Generated by Django 3.2.23 on 2023-12-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcessFoodApp', '0021_userrequest_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='food_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
