# Generated by Django 3.2.23 on 2023-12-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcessFoodApp', '0022_auto_20231227_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
