# Generated by Django 3.2.23 on 2023-12-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcessFoodApp', '0024_userrequest_is_read_by_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='un_read',
            field=models.IntegerField(null=True),
        ),
    ]
