# Generated by Django 3.2.23 on 2023-12-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcessFoodApp', '0028_alter_userrequest_donor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequest',
            name='donor',
        ),
        migrations.AddField(
            model_name='userrequest',
            name='is_read_by_donor',
            field=models.ManyToManyField(blank=True, related_name='read_requests', to='ExcessFoodApp.Donor'),
        ),
    ]
