# Generated by Django 3.2.23 on 2023-12-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcessFoodApp', '0029_auto_20231228_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='seen_donor',
            field=models.TextField(null=True),
        ),
    ]
