# Generated by Django 3.2.23 on 2023-12-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcessFoodApp', '0031_remove_userrequest_is_read_by_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
