# Generated by Django 3.2.23 on 2023-12-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcessFoodApp', '0032_alter_userrequest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='date',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
