# Generated by Django 3.2.23 on 2023-12-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcessFoodApp', '0033_alter_userrequest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
