# Generated by Django 3.2.23 on 2024-02-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcessFoodApp', '0036_auto_20240219_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='prepared_time',
            field=models.DateTimeField(null=True),
        ),
    ]
