# Generated by Django 3.2.23 on 2024-02-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcessFoodApp', '0038_alter_user_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='is_expaired',
        ),
        migrations.RemoveField(
            model_name='places',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='places',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='food',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
