# Generated by Django 3.2.24 on 2024-03-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcessFoodApp', '0040_alter_food_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='prepared_time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
