# Generated by Django 3.2.24 on 2024-03-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcessFoodApp', '0041_alter_food_prepared_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='prepared_time',
            field=models.DateTimeField(null=True),
        ),
    ]
