# Generated by Django 3.2.24 on 2024-03-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcessFoodApp', '0042_alter_food_prepared_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='updated_date',
            field=models.DateTimeField(null=True),
        ),
    ]
