# Generated by Django 3.2.23 on 2024-03-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcessFoodApp', '0043_auto_20240314_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_deleted',
            field=models.IntegerField(default=0),
        ),
    ]
